[2.6] Comunidade patch 07/07/2021
portabilis/ieducar pull request #769
Opened 2021-07-07 19:36 UTC by marcosoliveirasoares94

**DESCRIÇÃO:**

Foi implementado a correção da issue [751](https://github.com/portabilis/i-educar/issues/751) registrada no repositório [Portabilis/i-educar](https://github.com/portabilis/i-educar/)

**MELHORIAS**

Foi adicionado descrições e tipos em alguns registros da tabela settings

**AMBIENTE:**

Descreva o ambiente em que este pull request foi criado.

- Plataforma utilizada (Docker, instalação direta)
- Sistema operacional e versão (Ubuntu 16.04)
- Navegador e versão (Chrome 91)

2021-07-08 23:49 UTC, edersoares requested changes
@marcosoliveirasoares94 obrigado pela contribuição, se possível fazer os ajustes para fazermos o merge o/

2021-07-08 23:49 UTC, edersoares commented on database/migrations/2020_08_03_000000_populate_settings_table.php
> +        DB::table('public.settings')->insert($settings);
Eu sugiro simplificar, assim não precisa repetir muito as linhas e vai ficar mais fácil o CR o/

```suggestion
        $settings = [
            'legacy.app.name' => 'i-Educar',
        ];

        collect($settings)->each(function ($value, $key) {
            Setting::query()->updateOrCreate([
                'key' => $key,
            ], [
                'value' => $value,
            ]);
        });
```

2021-07-08 23:49 UTC, edersoares commented on database/migrations/2020_08_03_170501_atualiza_nomenclatura_dos_campos_da_tela_de_configuracoes.php
> +                    WHEN \'legacy.app.database.dbname\' THEN \'Nome da database\'
```suggestion
                    WHEN \'legacy.app.database.dbname\' THEN \'Nome do banco de dados\'
```

2021-07-08 23:49 UTC, edersoares commented on database/migrations/2020_08_03_170501_atualiza_nomenclatura_dos_campos_da_tela_de_configuracoes.php
> +                    WHEN \'legacy.app.entity.name\' THEN \'Nome da entidade\'
Mantém o original porque é usado o termo "Instituição" dentro do i-Educar

```suggestion
                    WHEN \'legacy.app.entity.name\' THEN \'Nome da instituição\'
```

2021-07-08 23:49 UTC, edersoares commented on database/migrations/2020_08_03_170501_atualiza_nomenclatura_dos_campos_da_tela_de_configuracoes.php
> +                    WHEN \'legacy.app.mailer.smtp.port\' THEN \'SPMT Porta\'
```suggestion
                    WHEN \'legacy.app.mailer.smtp.port\' THEN \'SMTP Porta\'
```

2021-07-09 18:55 UTC, marcosoliveirasoares94 commented on database/migrations/2020_08_03_000000_populate_settings_table.php
> +        DB::table('public.settings')->insert($settings);
Ajuste realizado @edersoares.

2021-07-09 18:56 UTC, marcosoliveirasoares94 commented on database/migrations/2020_08_03_170501_atualiza_nomenclatura_dos_campos_da_tela_de_configuracoes.php
> +                    WHEN \'legacy.app.database.dbname\' THEN \'Nome da database\'
Ajuste realizado @edersoares.

2021-07-09 18:56 UTC, marcosoliveirasoares94 commented on database/migrations/2020_08_03_170501_atualiza_nomenclatura_dos_campos_da_tela_de_configuracoes.php
> +                    WHEN \'legacy.app.entity.name\' THEN \'Nome da entidade\'
Ajuste realizado @edersoares

2021-07-09 18:59 UTC, marcosoliveirasoares94 commented on database/migrations/2020_08_03_170501_atualiza_nomenclatura_dos_campos_da_tela_de_configuracoes.php
> +                    WHEN \'legacy.app.mailer.smtp.port\' THEN \'SPMT Porta\'
Ajuste realizado @edersoares.

Aproveito para informar que adicionei 3 novas categorias, sendo elas:
11 - AWS - S3 Armazenamento
12 - Recaptcha v3
13 - SMTP - Configuração para envio de E-mail

Além de renomear a categoria 6 - Recaptcha para Recaptcha v2

Foi realizado a correção do tipo string para boolean e o valor, para os atributos:
legacy.code
legacy.display_errors

2021-07-09 20:36 UTC, edersoares approved these changes

2021-07-09 20:36 UTC, edersoares commented on database/migrations/2020_08_03_000000_populate_settings_table.php
> +                'updated_at' => date('Y-m-d H:i:s'),
Pode ser removido, é adicionado automaticamente pelo model

```suggestion
```

2021-07-12 21:34 UTC, edersoares requested changes

2021-07-12 21:34 UTC, edersoares commented on database/migrations/2020_08_03_000000_populate_settings_table.php
> +            'legacy.apis.secret_key' => null,
```suggestion
            'legacy.apis.access_key' => 'ieducar-access-key',
            'legacy.apis.secret_key' => 'ieducar-secret-key',
```

2021-07-12 21:34 UTC, edersoares commented on database/migrations/2020_08_03_000000_populate_settings_table.php
> +            'legacy.apis.secret_key' => null,
Credenciais padrões para a API

2021-07-12 21:59 UTC, edersoares approved these changes

2021-07-12 21:59 UTC, merged