[2.6] Boletim do professor não é gerado no iDiário
portabilis/ieducar pull request #772
Opened 2021-07-19 17:29 UTC by marcosoliveirasoares94

MENU:

Relatórios → Boletim do professor

DESCRIÇÃO:

Ao tentar gerar o relatório, o mesmo não é gerado e o sistema é redirecionado para a página de configuração da API

AMBIENTE:

Plataforma utilizada: instalação direta
Outros detalhes importantes: i-Diario 1.3.3

EVIDÊNCIA:

![image](https://user-images.githubusercontent.com/12193221/126201433-9a3569fa-c660-4f8e-a53c-c92a7bd8ecab.png)

2021-07-20 12:08 UTC, edersoares requested changes

2021-07-20 12:08 UTC, edersoares commented on ieducar/modules/Api/Views/ReportController.php
> +            #$boletimProfessorReport->addArg('modelo', $modelo);
Pode remover ao invés de comentar, também pode remover a linha 124.

```suggestion
```

2021-07-20 13:45 UTC, edersoares approved these changes

2021-07-20 13:45 UTC, edersoares commented
Obrigado @marcosoliveirasoares94.

2021-07-20 13:46 UTC, merged

2021-07-21 17:42 UTC, edersoares commented
@marcosoliveirasoares94 consegue validar se o funcionamento segue correto utilizando o código desta branch e do PR https://github.com/portabilis/i-educar-reports-package/pull/85?

Obrigado.

2021-07-21 18:40 UTC, marcosoliveirasoares94 commented
Olá @eberfreitas, farei o teste ainda hoje a noite e volto aqui para informar o resultado.

2021-07-22 16:13 UTC, marcosoliveirasoares94 commented
Olá @edersoares, realizei o testes e a funcionalidade continua 100%. Pode seguir com o PR.