fix: correções na instalação local com docker
portabilis/ieducar pull request #895
Opened 2023-01-27 14:48 UTC by thiagobarros2

Olá e obrigado por nos ajudar a tornar o i-Educar um projeto mais estável. Para abrir um pull request use o template abaixo:

**DESCRIÇÃO:**

Nesta seção deve ser colocado uma descrição do que está sendo implementado.

**AMBIENTE:**

Descreva o ambiente em que este pull request foi criado.

- Plataforma utilizada (Docker, instalação direta)
- Sistema operacional e versão (Ubuntu 16.04, Windows 7)
- Navegador e versão (Chrome 75)
- Outros detalhes importantes

2023-02-01 11:43 UTC, jrbarros commented
@thiagobarros2 muito obrigado pela contribuição. 

Ao fazer os testes no meu ambiente  `Ubuntu 22`, ocorreu tudo certinho, com a exceção da instação do docker-composer, pois eu uso esse comando separado. Instalei usando a recomentação do docker https://docs.docker.com/compose/install/linux/.

Temos um grande PR https://github.com/portabilis/i-educar/pull/883, que vai nos dar muitas melhorias. 

Podes ajudar a testar essas novas feature e ver se o erro que aconteceu com você ainda persiste nessa branch?

2023-03-10 17:10 UTC, edersoares requested changes

2023-03-10 17:10 UTC, edersoares commented on app/Services/Educacenso/Version2022/Registro00Import.php
> +            //     ->first();
```suggestion
            $district = District::where('city_id', $city->id)
                ->where('ibge_code', $ibge_code)
               ->first();
```

2023-03-10 17:10 UTC, edersoares commented on app/Services/Educacenso/Version2022/Registro00Import.php
> +            $school->iddis = 0;
```suggestion
            $school->iddis = district ? $district->getKey() : 0;
```

2023-03-10 17:10 UTC, edersoares commented on docker-compose.yml
> +      - 8000:80
Reverter todas alterações neste arquivo, para customização individual use o `docker-compose.override.yml` conforme a documentação.

2023-03-10 17:10 UTC, edersoares commented on README.md
> +docker exec ieducar-php composer new-install
Tendo o Docker Compose instalado o comando funciona normalmente, não vejo motivo de modificarmos.

2023-03-11 00:39 UTC, closed without merging